application: mitac-cheerspoint-v20150518
module: tasks
version: 1
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F4
automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 300ms
#  max_concurrent_requests: 80
#  max_idle_instances: automatica  # default value
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: app.router
  secure: always

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^ipwarmup_*.csv
