application: cage-20160705-edm
module: ownership
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /googleae8f4bcce8bec00c.html
  static_files: googleae8f4bcce8bec00c.html
  upload: googleae8f4bcce8bec00c.html